### ISSUE TITLE
代码优化

### ISSUE THREAD

**Issue by hust-tiny** [OpenDRG/DRG_Python#1]
目前项目对代码得用法就像在把代码当数据库一样在使用。既然用了.bat文件，为什么不把代码里面得那些诊断信息也存入.bat文件中？用了bat,考虑一下轻小型数据库？函数直接return true也是不被允许的，这样只会暴露项目开发者的能力不够。算法就那么点，代码跟算法有关的可能就几百行，剩下的全部是数据和逻辑判断，逻辑判断这么多可以考虑使用表驱动设计，表信息也可以存到数据库中。目前这个项目维护起来会很困难，而且项目也会吃内存。

**Comment by lelecat** [comment]
你好，感谢反馈。这款分组器是设计成为插件，在其他系统中集成的，为了把运行环境依赖降到最低，不能用数据库，也不用任何第三方组件，仅仅依赖编程语言的标准组件，例如python版只依赖python3，java版只依赖java8。数据存储方面，key-value形式的简单数据存入dat文件，更加复杂形式的数据就放在代码本身。这种设计确实会增加内存消耗，但这种消耗的成本极低。好处是逻辑清晰，维护简单，正确性易于验证。
