### ISSUE TITLE
drg_group/guangxi_2022/MDC/MDCJ.py

### ISSUE THREAD

**Issue by Biggg888** [OpenDRG/DRG_Python#2]
当我想运行 python -m drg_group.guangxi_2022.GroupTest "22077275,2,47,17377,,13100005,53,1,Z51.003|C34.900x001|Z51.100x004|Z51.801,92.2400x005,RC19"时，报错

ImportError: cannot import name 'JA1' from 'drg_group.guangxi_2022.ADRG' (unknown location)

在drg_group\guangxi_2022\ADRG\中 只有JA1_1.py、JA1_2.py

![image](https://github.com/OpenDRG/DRG_Python/assets/49727302/4646327b-4438-4272-a83d-5624356d4a80)

**Comment by OpenDRG** [comment]
你好，已修复

![image](https://github.com/OpenDRG/DRG_Python/assets/122415688/cdf9b223-3f44-4db2-ad61-ac0263de4a83)
